### ISSUE TITLE
dll dependencies  in windows

### ISSUE THREAD

**Issue by dalip9837056007** [xhimanshuz/AAA#3]
![image](https://user-images.githubusercontent.com/76249628/102688350-493a3100-421c-11eb-8d5c-b5dd563511d6.png)

**Comment by xhimanshuz** [comment]
Ok, All these DLL files required to execute an application on windows.

**Comment by xhimanshuz** [comment]
Fixed with Static build except for pdftron

**Comment by dalip9837056007** [comment]
done
